"""initial legal knowledge schema

Revision ID: 2fdcaa0173ae
Revises: 
Create Date: 2026-09-09 20:25:40.992260+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '2fdcaa0173ae'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Every native enum type this migration creates. Kept explicit because the
#: autogenerated downgrade does not clean them up.
ENUM_TYPES: tuple[str, ...] = (
    "authority_current_status",
    "authority_relation_type",
    "authority_type",
    "commercial_reuse_status",
    "copyright_status",
    "crawl_frequency",
    "crawl_status",
    "entity_type",
    "idea_part",
    "ingestion_status",
    "jurisdiction_type",
    "precedential_status",
    "proposition_authority_relation",
    "proposition_authority_status",
    "proposition_type",
    "retrieval_method",
    "review_status",
    "source_type",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction_type', sa.Enum('federal', 'state', 'district', 'territory', 'outlying_area', 'federal_agency', 'federal_circuit', name='jurisdiction_type'), nullable=False),
    sa.Column('postal_code', sa.String(length=2), nullable=True),
    sa.Column('parent_jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('federal_circuit', sa.String(length=16), nullable=True),
    sa.Column('sea_name', sa.String(length=255), nullable=True),
    sa.Column('idea_part_b_applicable', sa.Boolean(), nullable=False),
    sa.Column('idea_part_c_applicable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('parent_jurisdiction_id IS NULL OR parent_jurisdiction_id <> id', name=op.f('ck_jurisdiction_jurisdiction_not_own_parent')),
    sa.CheckConstraint('postal_code IS NULL OR postal_code = upper(postal_code)', name=op.f('ck_jurisdiction_postal_code_uppercase')),
    sa.ForeignKeyConstraint(['parent_jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_jurisdiction_parent_jurisdiction_id_jurisdiction'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction')),
    sa.UniqueConstraint('slug', name=op.f('uq_jurisdiction_slug'))
    )
    op.create_index('ix_jurisdiction_postal_code', 'jurisdiction', ['postal_code'], unique=False)
    op.create_index('ix_jurisdiction_type_active', 'jurisdiction', ['jurisdiction_type', 'active'], unique=False)
    op.create_table('legal_concept',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('idea_part', sa.Enum('part_a', 'part_b', 'part_c', 'part_d', 'cross_cutting', name='idea_part'), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_legal_concept_concept_not_own_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['legal_concept.id'], name=op.f('fk_legal_concept_parent_id_legal_concept'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_concept')),
    sa.UniqueConstraint('slug', name=op.f('uq_legal_concept_slug'))
    )
    op.create_index('ix_legal_concept_parent', 'legal_concept', ['parent_id'], unique=False)
    op.create_index('ix_legal_concept_part', 'legal_concept', ['idea_part'], unique=False)
    op.create_table('review_event',
    sa.Column('entity_type', sa.Enum('authority', 'authority_version', 'proposition', 'proposition_authority', 'authority_relationship', 'source', 'legal_concept', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=True),
    sa.Column('review_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_event'))
    )
    op.create_index('ix_review_event_created', 'review_event', ['created_at'], unique=False)
    op.create_index('ix_review_event_entity', 'review_event', ['entity_type', 'entity_id'], unique=False)
    op.create_table('proposition',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('qualifier', sa.Text(), nullable=True),
    sa.Column('proposition_type', sa.Enum('requirement', 'prohibition', 'definition', 'exception', 'deadline', 'procedure', 'standard', 'factor_test', 'allocation', name='proposition_type'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('authority_status', sa.Enum('binding_authority', 'persuasive_authority', 'agency_interpretation', 'contested', 'unsupported', name='proposition_authority_status'), nullable=False),
    sa.Column('review_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("(review_status <> 'human_reviewed' AND review_status <> 'expert_reviewed') OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_proposition_reviewed_records_name_a_reviewer')),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_proposition_confidence_range')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_proposition_proposition_dates_ordered')),
    sa.CheckConstraint('length(btrim(statement)) > 0', name=op.f('ck_proposition_statement_not_blank')),
    sa.ForeignKeyConstraint(['concept_id'], ['legal_concept.id'], name=op.f('fk_proposition_concept_id_legal_concept'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_proposition_jurisdiction_id_jurisdiction'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposition'))
    )
    op.create_index('ix_proposition_authority_status', 'proposition', ['authority_status'], unique=False)
    op.create_index('ix_proposition_concept_jurisdiction', 'proposition', ['concept_id', 'jurisdiction_id'], unique=False)
    op.create_index('ix_proposition_review_status', 'proposition', ['review_status'], unique=False)
    op.create_table('source',
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('statute', 'regulation', 'guidance', 'policy_letter', 'court_opinion', 'due_process_decision', 'state_complaint_decision', 'procedural_safeguards', 'form', 'dataset', 'other', name='source_type'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('retrieval_method', sa.Enum('http_html', 'http_pdf', 'http_json', 'api', 'bulk_download', 'manual', name='retrieval_method'), nullable=False),
    sa.Column('official_source', sa.Boolean(), nullable=False),
    sa.Column('copyright_status', sa.Enum('us_government_public_domain', 'government_edict', 'public_domain_other', 'proprietary', 'mixed', 'unknown', name='copyright_status'), nullable=False),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('commercial_reuse_status', sa.Enum('permitted', 'restricted', 'prohibited', 'requires_legal_review', 'unknown', name='commercial_reuse_status'), nullable=False),
    sa.Column('terms_of_service_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('crawl_frequency', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'annually', 'on_demand', name='crawl_frequency'), nullable=False),
    sa.Column('crawl_status', sa.Enum('not_started', 'urls_unverified', 'urls_verified', 'active', 'blocked', 'error', name='crawl_status'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_source_jurisdiction_id_jurisdiction'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('jurisdiction_id', 'name', name='uq_source_jurisdiction_name'),
    sa.UniqueConstraint('slug', name=op.f('uq_source_slug'))
    )
    op.create_index('ix_source_crawl_status', 'source', ['crawl_status'], unique=False)
    op.create_index('ix_source_type_active', 'source', ['source_type', 'active'], unique=False)
    op.create_table('authority',
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('authority_type', sa.Enum('federal_statute', 'federal_regulation', 'federal_guidance', 'osep_policy_letter', 'osep_memorandum', 'dear_colleague_letter', 'ocr_guidance', 'supreme_court_opinion', 'circuit_court_opinion', 'district_court_opinion', 'state_statute', 'state_regulation', 'state_guidance', 'state_court_opinion', 'procedural_safeguards_notice', 'due_process_decision', 'state_complaint_decision', 'other', name='authority_type'), nullable=False),
    sa.Column('canonical_citation', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_title', sa.String(length=255), nullable=True),
    sa.Column('docket_or_identifier', sa.String(length=255), nullable=True),
    sa.Column('court_or_agency', sa.String(length=255), nullable=True),
    sa.Column('idea_part', sa.Enum('part_a', 'part_b', 'part_c', 'part_d', 'cross_cutting', name='idea_part'), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.Enum('in_force', 'amended', 'repealed', 'superseded', 'proposed', 'withdrawn', 'unknown', name='authority_current_status'), nullable=False),
    sa.Column('precedential_status', sa.Enum('binding', 'persuasive', 'non_precedential', 'unpublished', 'not_applicable', 'unknown', name='precedential_status'), nullable=False),
    sa.Column('review_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('superseded_date IS NULL OR effective_date IS NULL OR superseded_date >= effective_date', name=op.f('ck_authority_authority_dates_ordered')),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.id'], name=op.f('fk_authority_jurisdiction_id_jurisdiction'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_authority_source_id_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authority')),
    sa.UniqueConstraint('jurisdiction_id', 'canonical_citation', name='uq_authority_jurisdiction_citation')
    )
    op.create_index('ix_authority_idea_part', 'authority', ['idea_part'], unique=False)
    op.create_index('ix_authority_jurisdiction_type', 'authority', ['jurisdiction_id', 'authority_type'], unique=False)
    op.create_index('ix_authority_type_status', 'authority', ['authority_type', 'current_status'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'partial', 'failed', 'skipped', name='ingestion_status'), nullable=False),
    sa.Column('documents_seen', sa.Integer(), nullable=False),
    sa.Column('changed_documents', sa.Integer(), nullable=False),
    sa.Column('unchanged_documents', sa.Integer(), nullable=False),
    sa.Column('new_documents', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('collector_name', sa.String(length=128), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_ingestion_run_ingestion_run_times_ordered')),
    sa.CheckConstraint('documents_seen >= 0 AND changed_documents >= 0 AND error_count >= 0', name=op.f('ck_ingestion_run_ingestion_run_counts_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_ingestion_run_source_id_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run'))
    )
    op.create_index('ix_ingestion_run_source_started', 'ingestion_run', ['source_id', 'started_at'], unique=False)
    op.create_index('ix_ingestion_run_status', 'ingestion_run', ['status'], unique=False)
    op.create_table('authority_relationship',
    sa.Column('source_authority_id', sa.Uuid(), nullable=False),
    sa.Column('target_authority_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('cites', 'interprets', 'supersedes', 'overrules', 'distinguishes', 'applies', 'implements', 'abrogates', name='authority_relation_type'), nullable=False),
    sa.Column('review_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('source_authority_id <> target_authority_id', name=op.f('ck_authority_relationship_authority_relationship_no_self_edge')),
    sa.ForeignKeyConstraint(['source_authority_id'], ['authority.id'], name=op.f('fk_authority_relationship_source_authority_id_authority'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_authority_id'], ['authority.id'], name=op.f('fk_authority_relationship_target_authority_id_authority'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authority_relationship')),
    sa.UniqueConstraint('source_authority_id', 'target_authority_id', 'relationship_type', name='uq_authority_relationship_edge')
    )
    op.create_index('ix_authority_relationship_target', 'authority_relationship', ['target_authority_id'], unique=False)
    op.create_table('authority_version',
    sa.Column('authority_id', sa.Uuid(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('parser_name', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('source_snapshot_url', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('needs_review', 'ai_extracted', 'source_verified', 'cross_validated', 'human_reviewed', 'expert_reviewed', 'rejected', name='review_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_authority_version_version_dates_ordered')),
    sa.CheckConstraint('length(raw_sha256) = 64', name=op.f('ck_authority_version_raw_sha256_length')),
    sa.CheckConstraint('length(sha256) = 64', name=op.f('ck_authority_version_sha256_length')),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], name=op.f('fk_authority_version_authority_id_authority'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authority_version')),
    sa.UniqueConstraint('authority_id', 'sha256', name='uq_authority_version_hash')
    )
    op.create_index('ix_authority_version_retrieved', 'authority_version', ['authority_id', 'retrieved_at'], unique=False)
    op.create_index('uq_authority_version_one_current', 'authority_version', ['authority_id'], unique=True, postgresql_where='is_current')
    op.create_table('proposition_authority',
    sa.Column('proposition_id', sa.Uuid(), nullable=False),
    sa.Column('authority_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('primary_support', 'supports', 'interprets', 'limits', 'contradicts', 'background', name='proposition_authority_relation'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('pin_cite', sa.String(length=255), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 100', name=op.f('ck_proposition_authority_weight_range')),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], name=op.f('fk_proposition_authority_authority_id_authority'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposition_id'], ['proposition.id'], name=op.f('fk_proposition_authority_proposition_id_proposition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposition_authority')),
    sa.UniqueConstraint('proposition_id', 'authority_id', 'relationship_type', name='uq_proposition_authority_edge')
    )
    op.create_index('ix_proposition_authority_authority', 'proposition_authority', ['authority_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposition_authority_authority', table_name='proposition_authority')
    op.drop_table('proposition_authority')
    op.drop_index('uq_authority_version_one_current', table_name='authority_version', postgresql_where='is_current')
    op.drop_index('ix_authority_version_retrieved', table_name='authority_version')
    op.drop_table('authority_version')
    op.drop_index('ix_authority_relationship_target', table_name='authority_relationship')
    op.drop_table('authority_relationship')
    op.drop_index('ix_ingestion_run_status', table_name='ingestion_run')
    op.drop_index('ix_ingestion_run_source_started', table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index('ix_authority_type_status', table_name='authority')
    op.drop_index('ix_authority_jurisdiction_type', table_name='authority')
    op.drop_index('ix_authority_idea_part', table_name='authority')
    op.drop_table('authority')
    op.drop_index('ix_source_type_active', table_name='source')
    op.drop_index('ix_source_crawl_status', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_proposition_review_status', table_name='proposition')
    op.drop_index('ix_proposition_concept_jurisdiction', table_name='proposition')
    op.drop_index('ix_proposition_authority_status', table_name='proposition')
    op.drop_table('proposition')
    op.drop_index('ix_review_event_entity', table_name='review_event')
    op.drop_index('ix_review_event_created', table_name='review_event')
    op.drop_table('review_event')
    op.drop_index('ix_legal_concept_part', table_name='legal_concept')
    op.drop_index('ix_legal_concept_parent', table_name='legal_concept')
    op.drop_table('legal_concept')
    op.drop_index('ix_jurisdiction_type_active', table_name='jurisdiction')
    op.drop_index('ix_jurisdiction_postal_code', table_name='jurisdiction')
    op.drop_table('jurisdiction')
    # ### end Alembic commands ###

    # Alembic autogenerate does not drop native PostgreSQL enum types, so a
    # downgrade would leave them behind and the next upgrade would fail with
    # "type already exists". Drop them explicitly, in one statement, after every
    # table that referenced them is gone.
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
